name: Email Action Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 24f2004829@ds.study.iitm.ac.in
        run: echo "Hello, world!"

